image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - export PROJECT_NAME=LibLala/LibLala.csproj
          - export TEST_NAME=LibLala.Unittests/LibLala.Unittests.csproj
          - dotnet restore $PROJECT_NAME
          - dotnet build $PROJECT_NAME
          - dotnet test $TEST_NAME --filter Category!=Integration
