name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: [ARM32]

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: cd TagReaderService && docker build . --file Dockerfile --tag tag-reader-service:$(date +%s)
